# Generated by Django 4.2.7 on 2025-12-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subproductos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisSubproducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=100)),
                ('volumen', models.FloatField(blank=True, null=True)),
                ('recomendacion_principal', models.CharField(max_length=255)),
                ('justificacion', models.TextField(blank=True)),
                ('datos_entrada', models.JSONField(default=dict)),
                ('resultados', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
