# Generated by Django 4.2.7 on 2025-11-19 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoResiduo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LotesResiduos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('humedad', models.DecimalField(decimal_places=2, help_text='Porcentaje de humedad', max_digits=5)),
                ('tamanio_particula', models.CharField(help_text='Ej: 5-10 mm', max_length=50)),
                ('contaminacion', models.TextField(blank=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('especie', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='residuos.especie')),
                ('tipo_residuo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residuos.tiporesiduo')),
            ],
        ),
    ]
