# Generated by Django 4.2.7 on 2025-11-19 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residuos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lotesresiduos',
            name='tamanio_particula',
        ),
    ]
