# Generated by Copilot on 2025-12-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maquinaria", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tipomaquinaria",
            name="codigo",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
