# Generated by Copilot on 2025-12-15

import re

from django.db import migrations


DEFAULT_TYPES = [
    ("chipeadora", "Chipeadora", "Equipo para producir chips."),
    ("descortezadora", "Descortezadora", "Equipo para remover corteza."),
    ("reprocesadora", "Reprocesadora", "Equipo para reprocesar material / segunda calidad."),
    ("finger_joint", "Finger-Joint", "Equipo para producir finger-joint / molduras."),
    ("caldera", "Caldera", "Equipo de caldera (biomasa)."),
    ("pelletizadora", "Peletizadora", "Equipo para pelletización."),
]

TIPO_N_MAP = {
    1: DEFAULT_TYPES[0],
    2: DEFAULT_TYPES[1],
    3: DEFAULT_TYPES[2],
    4: DEFAULT_TYPES[3],
    5: DEFAULT_TYPES[4],
    6: DEFAULT_TYPES[5],
}


def _normalize(s: str) -> str:
    return re.sub(r"\s+", " ", (s or "").strip().lower())


def forwards(apps, schema_editor):
    TipoMaquinaria = apps.get_model("maquinaria", "TipoMaquinaria")

    # 1) If DB already has generic rows like "Tipo 1", rename them in-place to avoid breaking FKs.
    for tipo in TipoMaquinaria.objects.all():
        name_norm = _normalize(tipo.nombre)
        m = re.match(r"^tipo\s*(\d+)$", name_norm)
        if not m:
            continue

        n = int(m.group(1))
        if n not in TIPO_N_MAP:
            continue

        codigo, nombre, descripcion = TIPO_N_MAP[n]

        # If another row already owns this codigo, do not create duplicates.
        other = TipoMaquinaria.objects.filter(codigo=codigo).exclude(id=tipo.id).first()
        if other:
            # Keep existing 'tipo' row as-is if collision exists.
            continue

        tipo.codigo = codigo
        tipo.nombre = nombre
        # Keep user-provided descripcion if it exists; otherwise seed a default.
        if not (tipo.descripcion or "").strip():
            tipo.descripcion = descripcion
        tipo.save(update_fields=["codigo", "nombre", "descripcion"])

    # 2) Ensure canonical types exist (create missing ones).
    for codigo, nombre, descripcion in DEFAULT_TYPES:
        TipoMaquinaria.objects.get_or_create(
            codigo=codigo,
            defaults={"nombre": nombre, "descripcion": descripcion},
        )


def backwards(apps, schema_editor):
    # Intentionally non-destructive: do not delete user data.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("maquinaria", "0002_tipomaquinaria_codigo"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
